### ISSUE TITLE
Add .user-settings.env to .gitignore

### ISSUE THREAD

**Issue by ksofa2** [netdash/netdash#26]
The `.user-settings.env` file should ignored by Git.

The documentation in the comments in that file (and the comments from `.defaults.env`) should be moved to README.md

**Comment by rbharadwaj9** [comment]
Doesn't `git update-index --skip-worktree` stick with the file?
That's how I have  `.user-settings.env` set up in my working directory. I thought that was the standard practice for a config file

**Comment by ksofa2** [comment]
I haven't used that approach before. Are there examples of projects that do it this way?

**Comment by rbharadwaj9** [comment]
Reading more into `update-index`, I feel it is used in a context of big projects where a developer would want to safely override config files. However, some other developer (Eg: Owner of the project) may want to change the config file globally between versions and he can do so. This is because using `update-index` changes only the local repository.

If we are confident with the file and expect minimal changes, adding to `.gitignore` would be better and we can force push whenever there's an important change.

**Comment by ksofa2** [comment]
I have something a little different in mind. I'll do a quick PR, that'll be the easiest way to explain what I'm thinking.

**Comment by ksofa2** [comment]
Hmm. It looks like Docker Compose needs all files listed in `env-files` to exist. That complicates things. I'm going to assign this issue to myself and think on it some more.

**Comment by jlost** [comment]
Resolved by #27
