### ISSUE TITLE
Use netaddr instead of ipaddress for ip adress ranges

### ISSUE THREAD

**Issue by Thespis377** [netdash/netdash#60]
ipaddress is a very useful module for IP Addressing in Python.  However, there are a few limitations to the package.  One of these limitations is the creation of IP Address ranges.  For example, if I want to have an IP Address from 192.0.2.1 - 192.0.2.14, it's difficult to represent this in an ipaddress object.  However, it's trivial in netaddr.  

>>> ip_list = list(iter_iprange('192.0.2.1', '192.0.2.14'))
>>> len(ip_list)
14
>>> ip_list
[IPAddress('192.0.2.1'), IPAddress('192.0.2.2'), ..., IPAddress('192.0.2.13'), IPAddress('192.0.2.14')]

Also, netaddr has native support for MAC Addresses.

**Comment by jlost** [comment]
Hey @Thespis377 , thanks for the suggestion!
My understanding is that the two libraries are interoperable, but I preferred the Python one because it's PEP standard and includes some (minor) changes to remain Pythonic. 
To your example, I can replicate that functionality like so:
```
>>> a = ip_address("10.10.10.10")
>>> b = ip_address("10.10.10.17")
>>> [ip_address(ip) for ip in range(int(a), int(b)+1)]
[IPv4Address('10.10.10.10'), IPv4Address('10.10.10.11'), IPv4Address('10.10.10.12'), IPv4Address('10.10.10.13'), IPv4Address('10.10.10.14'), IPv4Address('10.10.10.15'), IPv4Address('10.10.10.16'), IPv4Address('10.10.10.17')]
```

Not quite as pretty, but I think it works well enough for this use case.

**Comment by jlost** [comment]
Closing; we can revisit if new reasons to use netaddr come to light.
